/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.suez.user.synch.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import com.liferay.suez.user.synch.model.ExtRole;
import com.liferay.suez.user.synch.service.ExtRoleService;
import com.liferay.suez.user.synch.service.persistence.ExtCompanyPersistence;
import com.liferay.suez.user.synch.service.persistence.ExtRolePersistence;
import com.liferay.suez.user.synch.service.persistence.ExtUserFinder;
import com.liferay.suez.user.synch.service.persistence.ExtUserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the ext role remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.suez.user.synch.service.impl.ExtRoleServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.suez.user.synch.service.impl.ExtRoleServiceImpl
 * @see com.liferay.suez.user.synch.service.ExtRoleServiceUtil
 * @generated
 */
public abstract class ExtRoleServiceBaseImpl extends BaseServiceImpl
	implements ExtRoleService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.suez.user.synch.service.ExtRoleServiceUtil} to access the ext role remote service.
	 */

	/**
	 * Returns the ext company local service.
	 *
	 * @return the ext company local service
	 */
	public com.liferay.suez.user.synch.service.ExtCompanyLocalService getExtCompanyLocalService() {
		return extCompanyLocalService;
	}

	/**
	 * Sets the ext company local service.
	 *
	 * @param extCompanyLocalService the ext company local service
	 */
	public void setExtCompanyLocalService(
		com.liferay.suez.user.synch.service.ExtCompanyLocalService extCompanyLocalService) {
		this.extCompanyLocalService = extCompanyLocalService;
	}

	/**
	 * Returns the ext company remote service.
	 *
	 * @return the ext company remote service
	 */
	public com.liferay.suez.user.synch.service.ExtCompanyService getExtCompanyService() {
		return extCompanyService;
	}

	/**
	 * Sets the ext company remote service.
	 *
	 * @param extCompanyService the ext company remote service
	 */
	public void setExtCompanyService(
		com.liferay.suez.user.synch.service.ExtCompanyService extCompanyService) {
		this.extCompanyService = extCompanyService;
	}

	/**
	 * Returns the ext company persistence.
	 *
	 * @return the ext company persistence
	 */
	public ExtCompanyPersistence getExtCompanyPersistence() {
		return extCompanyPersistence;
	}

	/**
	 * Sets the ext company persistence.
	 *
	 * @param extCompanyPersistence the ext company persistence
	 */
	public void setExtCompanyPersistence(
		ExtCompanyPersistence extCompanyPersistence) {
		this.extCompanyPersistence = extCompanyPersistence;
	}

	/**
	 * Returns the ext role local service.
	 *
	 * @return the ext role local service
	 */
	public com.liferay.suez.user.synch.service.ExtRoleLocalService getExtRoleLocalService() {
		return extRoleLocalService;
	}

	/**
	 * Sets the ext role local service.
	 *
	 * @param extRoleLocalService the ext role local service
	 */
	public void setExtRoleLocalService(
		com.liferay.suez.user.synch.service.ExtRoleLocalService extRoleLocalService) {
		this.extRoleLocalService = extRoleLocalService;
	}

	/**
	 * Returns the ext role remote service.
	 *
	 * @return the ext role remote service
	 */
	public ExtRoleService getExtRoleService() {
		return extRoleService;
	}

	/**
	 * Sets the ext role remote service.
	 *
	 * @param extRoleService the ext role remote service
	 */
	public void setExtRoleService(ExtRoleService extRoleService) {
		this.extRoleService = extRoleService;
	}

	/**
	 * Returns the ext role persistence.
	 *
	 * @return the ext role persistence
	 */
	public ExtRolePersistence getExtRolePersistence() {
		return extRolePersistence;
	}

	/**
	 * Sets the ext role persistence.
	 *
	 * @param extRolePersistence the ext role persistence
	 */
	public void setExtRolePersistence(ExtRolePersistence extRolePersistence) {
		this.extRolePersistence = extRolePersistence;
	}

	/**
	 * Returns the ext user local service.
	 *
	 * @return the ext user local service
	 */
	public com.liferay.suez.user.synch.service.ExtUserLocalService getExtUserLocalService() {
		return extUserLocalService;
	}

	/**
	 * Sets the ext user local service.
	 *
	 * @param extUserLocalService the ext user local service
	 */
	public void setExtUserLocalService(
		com.liferay.suez.user.synch.service.ExtUserLocalService extUserLocalService) {
		this.extUserLocalService = extUserLocalService;
	}

	/**
	 * Returns the ext user remote service.
	 *
	 * @return the ext user remote service
	 */
	public com.liferay.suez.user.synch.service.ExtUserService getExtUserService() {
		return extUserService;
	}

	/**
	 * Sets the ext user remote service.
	 *
	 * @param extUserService the ext user remote service
	 */
	public void setExtUserService(
		com.liferay.suez.user.synch.service.ExtUserService extUserService) {
		this.extUserService = extUserService;
	}

	/**
	 * Returns the ext user persistence.
	 *
	 * @return the ext user persistence
	 */
	public ExtUserPersistence getExtUserPersistence() {
		return extUserPersistence;
	}

	/**
	 * Sets the ext user persistence.
	 *
	 * @param extUserPersistence the ext user persistence
	 */
	public void setExtUserPersistence(ExtUserPersistence extUserPersistence) {
		this.extUserPersistence = extUserPersistence;
	}

	/**
	 * Returns the ext user finder.
	 *
	 * @return the ext user finder
	 */
	public ExtUserFinder getExtUserFinder() {
		return extUserFinder;
	}

	/**
	 * Sets the ext user finder.
	 *
	 * @param extUserFinder the ext user finder
	 */
	public void setExtUserFinder(ExtUserFinder extUserFinder) {
		this.extUserFinder = extUserFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ExtRoleService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ExtRole.class;
	}

	protected String getModelClassName() {
		return ExtRole.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = extRolePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.suez.user.synch.service.ExtCompanyLocalService.class)
	protected com.liferay.suez.user.synch.service.ExtCompanyLocalService extCompanyLocalService;
	@BeanReference(type = com.liferay.suez.user.synch.service.ExtCompanyService.class)
	protected com.liferay.suez.user.synch.service.ExtCompanyService extCompanyService;
	@BeanReference(type = ExtCompanyPersistence.class)
	protected ExtCompanyPersistence extCompanyPersistence;
	@BeanReference(type = com.liferay.suez.user.synch.service.ExtRoleLocalService.class)
	protected com.liferay.suez.user.synch.service.ExtRoleLocalService extRoleLocalService;
	@BeanReference(type = ExtRoleService.class)
	protected ExtRoleService extRoleService;
	@BeanReference(type = ExtRolePersistence.class)
	protected ExtRolePersistence extRolePersistence;
	@BeanReference(type = com.liferay.suez.user.synch.service.ExtUserLocalService.class)
	protected com.liferay.suez.user.synch.service.ExtUserLocalService extUserLocalService;
	@BeanReference(type = com.liferay.suez.user.synch.service.ExtUserService.class)
	protected com.liferay.suez.user.synch.service.ExtUserService extUserService;
	@BeanReference(type = ExtUserPersistence.class)
	protected ExtUserPersistence extUserPersistence;
	@BeanReference(type = ExtUserFinder.class)
	protected ExtUserFinder extUserFinder;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}