/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.suez.user.synch.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ExtCompany service. Represents a row in the &quot;company&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.suez.user.synch.model.impl.ExtCompanyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.suez.user.synch.model.impl.ExtCompanyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExtCompany
 * @see com.liferay.suez.user.synch.model.impl.ExtCompanyImpl
 * @see com.liferay.suez.user.synch.model.impl.ExtCompanyModelImpl
 * @generated
 */
@ProviderType
public interface ExtCompanyModel extends BaseModel<ExtCompany>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ext company model instance should use the {@link ExtCompany} interface instead.
	 */

	/**
	 * Returns the primary key of this ext company.
	 *
	 * @return the primary key of this ext company
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ext company.
	 *
	 * @param primaryKey the primary key of this ext company
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the company ID of this ext company.
	 *
	 * @return the company ID of this ext company
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ext company.
	 *
	 * @param companyId the company ID of this ext company
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the account ID of this ext company.
	 *
	 * @return the account ID of this ext company
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this ext company.
	 *
	 * @param accountId the account ID of this ext company
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the web ID of this ext company.
	 *
	 * @return the web ID of this ext company
	 */
	@AutoEscape
	public String getWebId();

	/**
	 * Sets the web ID of this ext company.
	 *
	 * @param webId the web ID of this ext company
	 */
	public void setWebId(String webId);

	/**
	 * Returns the key of this ext company.
	 *
	 * @return the key of this ext company
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this ext company.
	 *
	 * @param key the key of this ext company
	 */
	public void setKey(String key);

	/**
	 * Returns the mx of this ext company.
	 *
	 * @return the mx of this ext company
	 */
	@AutoEscape
	public String getMx();

	/**
	 * Sets the mx of this ext company.
	 *
	 * @param mx the mx of this ext company
	 */
	public void setMx(String mx);

	/**
	 * Returns the home u r l of this ext company.
	 *
	 * @return the home u r l of this ext company
	 */
	@AutoEscape
	public String getHomeURL();

	/**
	 * Sets the home u r l of this ext company.
	 *
	 * @param homeURL the home u r l of this ext company
	 */
	public void setHomeURL(String homeURL);

	/**
	 * Returns the logo ID of this ext company.
	 *
	 * @return the logo ID of this ext company
	 */
	public long getLogoId();

	/**
	 * Sets the logo ID of this ext company.
	 *
	 * @param logoId the logo ID of this ext company
	 */
	public void setLogoId(long logoId);

	/**
	 * Returns the system of this ext company.
	 *
	 * @return the system of this ext company
	 */
	public boolean getSystem();

	/**
	 * Returns <code>true</code> if this ext company is system.
	 *
	 * @return <code>true</code> if this ext company is system; <code>false</code> otherwise
	 */
	public boolean isSystem();

	/**
	 * Sets whether this ext company is system.
	 *
	 * @param system the system of this ext company
	 */
	public void setSystem(boolean system);

	/**
	 * Returns the max users of this ext company.
	 *
	 * @return the max users of this ext company
	 */
	public int getMaxUsers();

	/**
	 * Sets the max users of this ext company.
	 *
	 * @param maxUsers the max users of this ext company
	 */
	public void setMaxUsers(int maxUsers);

	/**
	 * Returns the active of this ext company.
	 *
	 * @return the active of this ext company
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this ext company is active.
	 *
	 * @return <code>true</code> if this ext company is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this ext company is active.
	 *
	 * @param active the active of this ext company
	 */
	public void setActive(boolean active);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ExtCompany extCompany);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ExtCompany> toCacheModel();

	@Override
	public ExtCompany toEscapedModel();

	@Override
	public ExtCompany toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}